### ISSUE TITLE
GUI: login/logout issues

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#40]
Currently, if I am logged in as "peter" I cannot log in as "peter" in any other browser or window. Or, I can login but then it takes forever to load an exercise.

The same problem if I'm logged in and close that window. Then I have to restart the server.

**Comment by fredefox** [comment]
Hi Peter. I can't reproduce this. Can you give me the output of `git rev-parse HEAD` and could I get you to check the browser console (hit f12) for any giveaways.

**Comment by heatherleaf** [comment]
Sorry, can't reproduce either anymore. Almost, there is one way it stalls:

1. Start Chrome, log in to Muste as "peter"
2. Select a lesson, start playing
3. Start Firefox, log in to Muste as "peter" again
4. Select a lesson, start playing
5. Now the instance in Chrome is dead, but I can still play with Firefox

This is not a serious problem. But it's better if the previous running login session (Chrome) notices that the same user has logged in from another place (Firefox) and automatically logs out (i.e. shows the login screen)

Interestingly, if I log in to Muste as "peter" in two separate windows in Firefox, nothing dies... best would be if the old window noticed that another session has started and then auto-logs out. But perhaps that's too difficult.

**Comment by fredefox** [comment]
I've improved error reporting, so you can see what the issue is. The problem is that the other browser hijacks the session when you log in the second time. This is certainly the desired behavior because when you log in again a new session is created for you and this should invalidate the old one. We could of course change the UI so that it auto logs out when it realizes it has a stale session.

**Comment by heatherleaf** [comment]
Yes, I assumed so. Auto-out-logging is a good solution I think.

**Comment by fredefox** [comment]
I've fixed this on the branch `gui-improvements` that include various other changes. I'll update the Changelog so you can see a summary, if we can merge those in, then we can close this.

**Comment by heatherleaf** [comment]
Sorry, cannot test the latest improvements. The GUI stalls when I select a lesson, here's the Chrome console:

![image](https://user-images.githubusercontent.com/1324196/46154372-4cc8f280-c275-11e8-8c69-465aa28cdb1e.png)

**Comment by fredefox** [comment]
Hm.. That's strange. Can you make sure that you are on 297345d33ee9456664472b551a230182af547d70 and that the browser cache is clear? Ctrl+Shift+R reloads the page and skips the cache in chrome. I haven't seen that error and `undefined` is not very descriptive, now is it.

**Comment by fredefox** [comment]
Just noticed that I hadn't pushed this new branch. So that hopefully explains this.

**Comment by heatherleaf** [comment]
Nope, sorry. I'm at 297345d and no modified files, still the same problem. Here's what I did:

1. clean, build, run server:

```
$ stack clean

$ make grammars
make -C muste/data/grammars
for G in novo_modo ; do \
		make -C $G ; \
	done
make[2]: Nothing to be done for `all'.

$ stack build && stack install
Building all executables for `muste' once. After a successful build of all of them, only specified executables will be rebuilt.
muste-0.2.5.2: configure (lib + exe)
muste-0.2.5.2: build (lib + exe)
muste-0.2.5.2: copy/register
Building all executables for `muste-ajax' once. After a successful build of all of them, only specified executables will be rebuilt.
muste-ajax-0.2.5.2: configure (lib + exe)
muste-ajax-0.2.5.2: build (lib + exe)
muste-ajax-0.2.5.2: copy/register
Completed 2 action(s).          
Log files have been written to: /Users/peb/Documents/Repositories/MULLE/.stack-work/logs/
Copying from /Users/peb/Documents/Repositories/MULLE/.stack-work/install/x86_64-osx/lts-12.10/8.4.3/bin/muste to /Users/peb/.local/bin/muste
Copying from /Users/peb/Documents/Repositories/MULLE/.stack-work/install/x86_64-osx/lts-12.10/8.4.3/bin/muste-ajax to /Users/peb/.local/bin/muste-ajax

Copied executables to /Users/peb/.local/bin:
- muste
- muste-ajax

$ muste-ajax --recreate-db
[Configurations options]
virtual-root: ''
www-root: /Users/peb/Documents/Repositories/MULLE/.stack-work/install/x86_64-osx/lts-12.10/8.4.3/share/x86_64-osx-ghc-8.4.3/muste-ajax-0.2.5.2/www
static-dir: ./muste-ajax/static/
access-log: ./access.log
db: /Users/peb/Documents/Repositories/MULLE/.stack-work/install/x86_64-osx/lts-12.10/8.4.3/share/x86_64-osx-ghc-8.4.3/muste-ajax-0.2.5.2/data/muste.sqlite3
port: 8080
error-log: ./error.log

Initializing database...
Initializing database... done
Listening on http://0.0.0.0:8080
```

2. (in Firefox, but the same problem in all browsers) logging in, first selecting Exemplum Pars and the Prima Pars. Nothing happens att all but an error is thrown in the console for every click. Here's a screenshot:

![image](https://user-images.githubusercontent.com/1324196/46175136-45244080-c2ab-11e8-814c-21688a3939c1.png)

3. printing the contents of the log files after first trying Exemplum and then Prima:

```
$ cat error.log 

$ cat access.log 
127.0.0.1 - - [27/Sep/2018:23:09:26 +0200] "GET / HTTP/1.1" 200 900 - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0"
127.0.0.1 - - [27/Sep/2018:23:09:26 +0200] "GET /jquery.min.js HTTP/1.1" 200 30557 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0"
127.0.0.1 - - [27/Sep/2018:23:09:26 +0200] "GET /countdown.js HTTP/1.1" 200 6221 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0"
127.0.0.1 - - [27/Sep/2018:23:09:26 +0200] "GET /muste.css HTTP/1.1" 200 1599 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0"
127.0.0.1 - - [27/Sep/2018:23:09:27 +0200] "GET /muste-gui.js HTTP/1.1" 200 6370 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0"
127.0.0.1 - - [27/Sep/2018:23:09:27 +0200] "GET /handlebars.min.js HTTP/1.1" 200 22828 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0"
127.0.0.1 - - [27/Sep/2018:23:09:36 +0200] "POST /api/login/ HTTP/1.1" 200 174 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0"
127.0.0.1 - - [27/Sep/2018:23:09:36 +0200] "POST /api/lessons/ HTTP/1.1" 200 285 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0"
127.0.0.1 - - [27/Sep/2018:23:09:47 +0200] "POST /api/lesson/Exemplum%20Pars HTTP/1.1" 200 1654 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0"
127.0.0.1 - - [27/Sep/2018:23:10:06 +0200] "POST /api/lesson/Prima%20Pars HTTP/1.1" 200 1653 "http://0.0.0.0:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0"
```

**Comment by heatherleaf** [comment]
Did some more testing: the bug is introduced in 0357f9a 

Here are screenshots from Safari, Firefox and Chrome:

![image](https://user-images.githubusercontent.com/1324196/46190824-61e56600-c2f5-11e8-993f-4d1d2dcb5d74.png)

![image](https://user-images.githubusercontent.com/1324196/46190840-6e69be80-c2f5-11e8-8f72-c59ae2415ad6.png)

![image](https://user-images.githubusercontent.com/1324196/46190842-70cc1880-c2f5-11e8-8658-9b0bf21e3e53.png)

**Comment by heatherleaf** [comment]
Perhaps something with Handlebars? Because line 121 is in `Handlebars.registerHelper()`

**Comment by fredefox** [comment]
Ah I see you have a mac. Could this be the reason I can't reproduce?

**Comment by fredefox** [comment]
Your last comment gave me the clue. Should be fixed in b029ec0131e45295fcc8465a2e2f604a31f37913.

**Comment by heatherleaf** [comment]
Dang, still not working...

![image](https://user-images.githubusercontent.com/1324196/46215642-3044bd00-c33e-11e8-8c05-8059fea1d5f3.png)

(Happens ca 1-3 secs after I click the "Solve" button, so the server probably gets the request and sends the response)

Line 139 in `app.js` is the call to `console.error` here:

```
function handle_server_fail(resp) {
  switch(resp.status) {
  case 401:
    show_page('loginpage');
    break;
  case 400:
  default: console.error(resp.responseJSON);
  }
}
```

**Comment by heatherleaf** [comment]
Same error in Firefox, Chrome and Safari

**Comment by fredefox** [comment]
I really wanna fix this today. Can you try the same procedure with 44f777913f2a018cf2a23e1fced93165f84cba80 ?

**Comment by fredefox** [comment]
Another protip. You can open the "Network" tab in the developer console of Chrome. There might be some more leads there. Look for requests highlighted in red. Have a look at e.g. the response tab of that request.

**Comment by fredefox** [comment]
That branch have some untested features, so there are some other problems that I just discovered. Sorry about that.

**Comment by heatherleaf** [comment]
Still not. Here's the network tab from Chrome:

![image](https://user-images.githubusercontent.com/1324196/46276591-dc65ee00-c560-11e8-831f-42ccb1ad468b.png)

**Comment by fredefox** [comment]
And no info in the log? What does it say when you click the red request? status=canceled, never seen that before... I've pushed a new commit 79b9bc19177c665d75751e1a33aa3084a1220cef

**Comment by fredefox** [comment]
For reference: https://stackoverflow.com/questions/12009423/what-does-status-canceled-for-a-resource-mean-in-chrome-developer-tools

Looks super strange.

**Comment by fredefox** [comment]
Off the top of the head the biggest changes I did in this department was to slap `defer` on the script tags and made ajax calls asynchronous. I don't see how this should be the root cause, though.

**Comment by fredefox** [comment]
In dev-tools could you go to settings and under "Network" make sure the box labeled "Disable chache" is checked?

**Comment by fredefox** [comment]
I think maybe I'm seeing this as well. The problem seem to appear the first time after you request a lesson after running with `--recreate-db` it does not happen on subsequent requests. The reason given for the failure is a timeout. Very strange...

**Comment by fredefox** [comment]
More info: The server is receiving the request, processing it and generating a valid response. The issue seems to be on the front-end.

**Comment by fredefox** [comment]
Can you try with adb4e4e888c95be9a21e392f4d9b76cdb9984746

**Comment by heatherleaf** [comment]
yay! now it works!

**Comment by heatherleaf** [comment]
you removed the timeout -- do you think there might be other problems because of that?

**Comment by fredefox** [comment]
Addendum: 1s is a very high bar for a timeout I would say. 1s is a good aim for a response time, but we shouldn't loose our patience and just give up after 1s.

**Comment by fredefox** [comment]
Looks like the default is to wait forever:

https://github.com/jquery/jquery/blob/dfa92ccead70d7dd5735a36c6d0dd1af680271cd/src/ajax.js#L312

**Comment by heatherleaf** [comment]
I think this is fine, closing
